/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Client;
using Jacrys.AthenaSharp.Model;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing Analyte
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnalyteTests
    {
        // TODO uncomment below to declare an instance variable for Analyte
        //private Analyte instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Analyte
            //instance = new Analyte();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Analyte
        /// </summary>
        [Test]
        public void AnalyteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Analyte
            //Assert.IsInstanceOfType<Analyte> (instance, "variable 'instance' is a Analyte");
        }


        /// <summary>
        /// Test the property 'Analyteid'
        /// </summary>
        [Test]
        public void AnalyteidTest()
        {
            // TODO unit test for the property 'Analyteid'
        }
        /// <summary>
        /// Test the property 'Analytename'
        /// </summary>
        [Test]
        public void AnalytenameTest()
        {
            // TODO unit test for the property 'Analytename'
        }
        /// <summary>
        /// Test the property 'Loinc'
        /// </summary>
        [Test]
        public void LoincTest()
        {
            // TODO unit test for the property 'Loinc'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Test]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Analytedate'
        /// </summary>
        [Test]
        public void AnalytedateTest()
        {
            // TODO unit test for the property 'Analytedate'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Abnormalflag'
        /// </summary>
        [Test]
        public void AbnormalflagTest()
        {
            // TODO unit test for the property 'Abnormalflag'
        }
        /// <summary>
        /// Test the property 'Abnormalhl7code'
        /// </summary>
        [Test]
        public void Abnormalhl7codeTest()
        {
            // TODO unit test for the property 'Abnormalhl7code'
        }
        /// <summary>
        /// Test the property 'Abnormalhl7name'
        /// </summary>
        [Test]
        public void Abnormalhl7nameTest()
        {
            // TODO unit test for the property 'Abnormalhl7name'
        }
        /// <summary>
        /// Test the property 'Valuestatus'
        /// </summary>
        [Test]
        public void ValuestatusTest()
        {
            // TODO unit test for the property 'Valuestatus'
        }
        /// <summary>
        /// Test the property 'Referencerange'
        /// </summary>
        [Test]
        public void ReferencerangeTest()
        {
            // TODO unit test for the property 'Referencerange'
        }
        /// <summary>
        /// Test the property 'Resultstatus'
        /// </summary>
        [Test]
        public void ResultstatusTest()
        {
            // TODO unit test for the property 'Resultstatus'
        }
        /// <summary>
        /// Test the property 'Labresultstatus'
        /// </summary>
        [Test]
        public void LabresultstatusTest()
        {
            // TODO unit test for the property 'Labresultstatus'
        }

    }

}
