/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AppointmentClaim
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppointmentClaimTests
    {
        // TODO uncomment below to declare an instance variable for AppointmentClaim
        //private AppointmentClaim instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppointmentClaim
            //instance = new AppointmentClaim();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppointmentClaim
        /// </summary>
        [Test]
        public void AppointmentClaimInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppointmentClaim
            //Assert.IsInstanceOfType<AppointmentClaim> (instance, "variable 'instance' is a AppointmentClaim");
        }


        /// <summary>
        /// Test the property 'Referringproviderid'
        /// </summary>
        [Test]
        public void ReferringprovideridTest()
        {
            // TODO unit test for the property 'Referringproviderid'
        }
        /// <summary>
        /// Test the property 'Primaryinsurancepayer'
        /// </summary>
        [Test]
        public void PrimaryinsurancepayerTest()
        {
            // TODO unit test for the property 'Primaryinsurancepayer'
        }
        /// <summary>
        /// Test the property 'Secondaryinsurancepayer'
        /// </summary>
        [Test]
        public void SecondaryinsurancepayerTest()
        {
            // TODO unit test for the property 'Secondaryinsurancepayer'
        }
        /// <summary>
        /// Test the property 'Diagnoses'
        /// </summary>
        [Test]
        public void DiagnosesTest()
        {
            // TODO unit test for the property 'Diagnoses'
        }
        /// <summary>
        /// Test the property 'Claimcreateddate'
        /// </summary>
        [Test]
        public void ClaimcreateddateTest()
        {
            // TODO unit test for the property 'Claimcreateddate'
        }
        /// <summary>
        /// Test the property 'Procedures'
        /// </summary>
        [Test]
        public void ProceduresTest()
        {
            // TODO unit test for the property 'Procedures'
        }
        /// <summary>
        /// Test the property 'Billedservicedate'
        /// </summary>
        [Test]
        public void BilledservicedateTest()
        {
            // TODO unit test for the property 'Billedservicedate'
        }
        /// <summary>
        /// Test the property 'Billedproviderid'
        /// </summary>
        [Test]
        public void BilledprovideridTest()
        {
            // TODO unit test for the property 'Billedproviderid'
        }
        /// <summary>
        /// Test the property 'Appointmentid'
        /// </summary>
        [Test]
        public void AppointmentidTest()
        {
            // TODO unit test for the property 'Appointmentid'
        }
        /// <summary>
        /// Test the property 'Chargeamount'
        /// </summary>
        [Test]
        public void ChargeamountTest()
        {
            // TODO unit test for the property 'Chargeamount'
        }
        /// <summary>
        /// Test the property 'Transactionid'
        /// </summary>
        [Test]
        public void TransactionidTest()
        {
            // TODO unit test for the property 'Transactionid'
        }
        /// <summary>
        /// Test the property 'Claimid'
        /// </summary>
        [Test]
        public void ClaimidTest()
        {
            // TODO unit test for the property 'Claimid'
        }

    }

}
