/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Client;
using Jacrys.AthenaSharp.Model;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing AppointmentList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppointmentListTests
    {
        // TODO uncomment below to declare an instance variable for AppointmentList
        //private AppointmentList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppointmentList
            //instance = new AppointmentList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppointmentList
        /// </summary>
        [Test]
        public void AppointmentListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppointmentList
            //Assert.IsInstanceOfType<AppointmentList> (instance, "variable 'instance' is a AppointmentList");
        }


        /// <summary>
        /// Test the property 'Totalcount'
        /// </summary>
        [Test]
        public void TotalcountTest()
        {
            // TODO unit test for the property 'Totalcount'
        }
        /// <summary>
        /// Test the property 'Appointments'
        /// </summary>
        [Test]
        public void AppointmentsTest()
        {
            // TODO unit test for the property 'Appointments'
        }

    }

}
