/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Client;
using Jacrys.AthenaSharp.Model;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing AppointmentIds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppointmentIdsTests
    {
        // TODO uncomment below to declare an instance variable for AppointmentIds
        //private AppointmentIds instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppointmentIds
            //instance = new AppointmentIds();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppointmentIds
        /// </summary>
        [Test]
        public void AppointmentIdsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppointmentIds
            //Assert.IsInstanceOfType<AppointmentIds> (instance, "variable 'instance' is a AppointmentIds");
        }



    }

}
