/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body5
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body5Tests
    {
        // TODO uncomment below to declare an instance variable for Body5
        //private Body5 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body5
            //instance = new Body5();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body5
        /// </summary>
        [Test]
        public void Body5InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body5
            //Assert.IsInstanceOfType<Body5> (instance, "variable 'instance' is a Body5");
        }


        /// <summary>
        /// Test the property 'Appointmentdate'
        /// </summary>
        [Test]
        public void AppointmentdateTest()
        {
            // TODO unit test for the property 'Appointmentdate'
        }
        /// <summary>
        /// Test the property 'Appointmenttime'
        /// </summary>
        [Test]
        public void AppointmenttimeTest()
        {
            // TODO unit test for the property 'Appointmenttime'
        }
        /// <summary>
        /// Test the property 'Appointmenttypeid'
        /// </summary>
        [Test]
        public void AppointmenttypeidTest()
        {
            // TODO unit test for the property 'Appointmenttypeid'
        }
        /// <summary>
        /// Test the property 'Departmentid'
        /// </summary>
        [Test]
        public void DepartmentidTest()
        {
            // TODO unit test for the property 'Departmentid'
        }
        /// <summary>
        /// Test the property 'Providerid'
        /// </summary>
        [Test]
        public void ProvideridTest()
        {
            // TODO unit test for the property 'Providerid'
        }
        /// <summary>
        /// Test the property 'Reasonid'
        /// </summary>
        [Test]
        public void ReasonidTest()
        {
            // TODO unit test for the property 'Reasonid'
        }

    }

}
