/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Body6
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body6Tests
    {
        // TODO uncomment below to declare an instance variable for Body6
        //private Body6 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body6
            //instance = new Body6();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body6
        /// </summary>
        [Test]
        public void Body6InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body6
            //Assert.IsInstanceOfType<Body6> (instance, "variable 'instance' is a Body6");
        }


        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'Generic'
        /// </summary>
        [Test]
        public void GenericTest()
        {
            // TODO unit test for the property 'Generic'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Patient'
        /// </summary>
        [Test]
        public void PatientTest()
        {
            // TODO unit test for the property 'Patient'
        }
        /// <summary>
        /// Test the property 'Shortname'
        /// </summary>
        [Test]
        public void ShortnameTest()
        {
            // TODO unit test for the property 'Shortname'
        }
        /// <summary>
        /// Test the property 'Templatetypeonly'
        /// </summary>
        [Test]
        public void TemplatetypeonlyTest()
        {
            // TODO unit test for the property 'Templatetypeonly'
        }

    }

}
