/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing Body7
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class Body7Tests
    {
        // TODO uncomment below to declare an instance variable for Body7
        //private Body7 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Body7
            //instance = new Body7();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Body7
        /// </summary>
        [Test]
        public void Body7InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Body7
            //Assert.IsInstanceOfType<Body7> (instance, "variable 'instance' is a Body7");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Startdate'
        /// </summary>
        [Test]
        public void StartdateTest()
        {
            // TODO unit test for the property 'Startdate'
        }
        /// <summary>
        /// Test the property 'Snomedcode'
        /// </summary>
        [Test]
        public void SnomedcodeTest()
        {
            // TODO unit test for the property 'Snomedcode'
        }
        /// <summary>
        /// Test the property 'Departmentid'
        /// </summary>
        [Test]
        public void DepartmentidTest()
        {
            // TODO unit test for the property 'Departmentid'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Laterality'
        /// </summary>
        [Test]
        public void LateralityTest()
        {
            // TODO unit test for the property 'Laterality'
        }

    }

}
