/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing CreateLabResultDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateLabResultDocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for CreateLabResultDocumentResponse
        //private CreateLabResultDocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateLabResultDocumentResponse
            //instance = new CreateLabResultDocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateLabResultDocumentResponse
        /// </summary>
        [Test]
        public void CreateLabResultDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateLabResultDocumentResponse
            //Assert.IsInstanceOfType<CreateLabResultDocumentResponse> (instance, "variable 'instance' is a CreateLabResultDocumentResponse");
        }


        /// <summary>
        /// Test the property 'Labresultid'
        /// </summary>
        [Test]
        public void LabresultidTest()
        {
            // TODO unit test for the property 'Labresultid'
        }
        /// <summary>
        /// Test the property 'Errormessage'
        /// </summary>
        [Test]
        public void ErrormessageTest()
        {
            // TODO unit test for the property 'Errormessage'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
