/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeleteLabResultDocumentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeleteLabResultDocumentResponseTests
    {
        // TODO uncomment below to declare an instance variable for DeleteLabResultDocumentResponse
        //private DeleteLabResultDocumentResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeleteLabResultDocumentResponse
            //instance = new DeleteLabResultDocumentResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeleteLabResultDocumentResponse
        /// </summary>
        [Test]
        public void DeleteLabResultDocumentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeleteLabResultDocumentResponse
            //Assert.IsInstanceOfType<DeleteLabResultDocumentResponse> (instance, "variable 'instance' is a DeleteLabResultDocumentResponse");
        }


        /// <summary>
        /// Test the property 'Labresultid'
        /// </summary>
        [Test]
        public void LabresultidTest()
        {
            // TODO unit test for the property 'Labresultid'
        }
        /// <summary>
        /// Test the property 'Errormessage'
        /// </summary>
        [Test]
        public void ErrormessageTest()
        {
            // TODO unit test for the property 'Errormessage'
        }
        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Test]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

    }

}
