/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Dosage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DosageTests
    {
        // TODO uncomment below to declare an instance variable for Dosage
        //private Dosage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Dosage
            //instance = new Dosage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Dosage
        /// </summary>
        [Test]
        public void DosageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Dosage
            //Assert.IsInstanceOfType<Dosage> (instance, "variable 'instance' is a Dosage");
        }


        /// <summary>
        /// Test the property 'Dosageaction'
        /// </summary>
        [Test]
        public void DosageactionTest()
        {
            // TODO unit test for the property 'Dosageaction'
        }
        /// <summary>
        /// Test the property 'Dosagequantityvalue'
        /// </summary>
        [Test]
        public void DosagequantityvalueTest()
        {
            // TODO unit test for the property 'Dosagequantityvalue'
        }
        /// <summary>
        /// Test the property 'Dosagequantityunit'
        /// </summary>
        [Test]
        public void DosagequantityunitTest()
        {
            // TODO unit test for the property 'Dosagequantityunit'
        }
        /// <summary>
        /// Test the property 'Dosagefrequencyvalue'
        /// </summary>
        [Test]
        public void DosagefrequencyvalueTest()
        {
            // TODO unit test for the property 'Dosagefrequencyvalue'
        }
        /// <summary>
        /// Test the property 'Dosagefrequencyunit'
        /// </summary>
        [Test]
        public void DosagefrequencyunitTest()
        {
            // TODO unit test for the property 'Dosagefrequencyunit'
        }
        /// <summary>
        /// Test the property 'Dosagefrequencydescription'
        /// </summary>
        [Test]
        public void DosagefrequencydescriptionTest()
        {
            // TODO unit test for the property 'Dosagefrequencydescription'
        }
        /// <summary>
        /// Test the property 'Dosageroute'
        /// </summary>
        [Test]
        public void DosagerouteTest()
        {
            // TODO unit test for the property 'Dosageroute'
        }
        /// <summary>
        /// Test the property 'Dosageadditionalinstructions'
        /// </summary>
        [Test]
        public void DosageadditionalinstructionsTest()
        {
            // TODO unit test for the property 'Dosageadditionalinstructions'
        }
        /// <summary>
        /// Test the property 'Dosagedurationvalue'
        /// </summary>
        [Test]
        public void DosagedurationvalueTest()
        {
            // TODO unit test for the property 'Dosagedurationvalue'
        }
        /// <summary>
        /// Test the property 'Dosagedurationunit'
        /// </summary>
        [Test]
        public void DosagedurationunitTest()
        {
            // TODO unit test for the property 'Dosagedurationunit'
        }

    }

}
