/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EncounterDiagnosis
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EncounterDiagnosisTests
    {
        // TODO uncomment below to declare an instance variable for EncounterDiagnosis
        //private EncounterDiagnosis instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EncounterDiagnosis
            //instance = new EncounterDiagnosis();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EncounterDiagnosis
        /// </summary>
        [Test]
        public void EncounterDiagnosisInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EncounterDiagnosis
            //Assert.IsInstanceOfType<EncounterDiagnosis> (instance, "variable 'instance' is a EncounterDiagnosis");
        }


        /// <summary>
        /// Test the property 'Diagnosisicd'
        /// </summary>
        [Test]
        public void DiagnosisicdTest()
        {
            // TODO unit test for the property 'Diagnosisicd'
        }
        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Test]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }
        /// <summary>
        /// Test the property 'Diagnosissnomed'
        /// </summary>
        [Test]
        public void DiagnosissnomedTest()
        {
            // TODO unit test for the property 'Diagnosissnomed'
        }
        /// <summary>
        /// Test the property 'Diagnosis'
        /// </summary>
        [Test]
        public void DiagnosisTest()
        {
            // TODO unit test for the property 'Diagnosis'
        }

    }

}
