/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing MessageResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageResultTests
    {
        // TODO uncomment below to declare an instance variable for MessageResult
        //private MessageResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageResult
            //instance = new MessageResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageResult
        /// </summary>
        [Test]
        public void MessageResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageResult
            //Assert.IsInstanceOfType<MessageResult> (instance, "variable 'instance' is a MessageResult");
        }


        /// <summary>
        /// Test the property 'Messagetype'
        /// </summary>
        [Test]
        public void MessagetypeTest()
        {
            // TODO unit test for the property 'Messagetype'
        }
        /// <summary>
        /// Test the property 'Calltime'
        /// </summary>
        [Test]
        public void CalltimeTest()
        {
            // TODO unit test for the property 'Calltime'
        }
        /// <summary>
        /// Test the property 'Messageresultid'
        /// </summary>
        [Test]
        public void MessageresultidTest()
        {
            // TODO unit test for the property 'Messageresultid'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
