/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PatientEncounterDiagnosis
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientEncounterDiagnosisTests
    {
        // TODO uncomment below to declare an instance variable for PatientEncounterDiagnosis
        //private PatientEncounterDiagnosis instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientEncounterDiagnosis
            //instance = new PatientEncounterDiagnosis();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientEncounterDiagnosis
        /// </summary>
        [Test]
        public void PatientEncounterDiagnosisInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientEncounterDiagnosis
            //Assert.IsInstanceOfType<PatientEncounterDiagnosis> (instance, "variable 'instance' is a PatientEncounterDiagnosis");
        }


        /// <summary>
        /// Test the property 'Diagnosisid'
        /// </summary>
        [Test]
        public void DiagnosisidTest()
        {
            // TODO unit test for the property 'Diagnosisid'
        }
        /// <summary>
        /// Test the property 'Icdcodes'
        /// </summary>
        [Test]
        public void IcdcodesTest()
        {
            // TODO unit test for the property 'Icdcodes'
        }
        /// <summary>
        /// Test the property 'Snomedcode'
        /// </summary>
        [Test]
        public void SnomedcodeTest()
        {
            // TODO unit test for the property 'Snomedcode'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
