/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PatientMedicalHistoryQuestion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientMedicalHistoryQuestionTests
    {
        // TODO uncomment below to declare an instance variable for PatientMedicalHistoryQuestion
        //private PatientMedicalHistoryQuestion instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientMedicalHistoryQuestion
            //instance = new PatientMedicalHistoryQuestion();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientMedicalHistoryQuestion
        /// </summary>
        [Test]
        public void PatientMedicalHistoryQuestionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientMedicalHistoryQuestion
            //Assert.IsInstanceOfType<PatientMedicalHistoryQuestion> (instance, "variable 'instance' is a PatientMedicalHistoryQuestion");
        }


        /// <summary>
        /// Test the property 'Questionid'
        /// </summary>
        [Test]
        public void QuestionidTest()
        {
            // TODO unit test for the property 'Questionid'
        }
        /// <summary>
        /// Test the property 'Question'
        /// </summary>
        [Test]
        public void QuestionTest()
        {
            // TODO unit test for the property 'Question'
        }
        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Test]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'Diagnosiscode'
        /// </summary>
        [Test]
        public void DiagnosiscodeTest()
        {
            // TODO unit test for the property 'Diagnosiscode'
        }
        /// <summary>
        /// Test the property 'Codeset'
        /// </summary>
        [Test]
        public void CodesetTest()
        {
            // TODO unit test for the property 'Codeset'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
