/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing PatientVital
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientVitalTests
    {
        // TODO uncomment below to declare an instance variable for PatientVital
        //private PatientVital instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientVital
            //instance = new PatientVital();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientVital
        /// </summary>
        [Test]
        public void PatientVitalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientVital
            //Assert.IsInstanceOfType<PatientVital> (instance, "variable 'instance' is a PatientVital");
        }


        /// <summary>
        /// Test the property 'Readings'
        /// </summary>
        [Test]
        public void ReadingsTest()
        {
            // TODO unit test for the property 'Readings'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Abbreviation'
        /// </summary>
        [Test]
        public void AbbreviationTest()
        {
            // TODO unit test for the property 'Abbreviation'
        }
        /// <summary>
        /// Test the property 'Ordering'
        /// </summary>
        [Test]
        public void OrderingTest()
        {
            // TODO unit test for the property 'Ordering'
        }

    }

}
