/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Patient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientTests
    {
        // TODO uncomment below to declare an instance variable for Patient
        //private Patient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Patient
            //instance = new Patient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Patient
        /// </summary>
        [Test]
        public void PatientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Patient
            //Assert.IsInstanceOfType<Patient> (instance, "variable 'instance' is a Patient");
        }


        /// <summary>
        /// Test the property 'Homeboundyn'
        /// </summary>
        [Test]
        public void HomeboundynTest()
        {
            // TODO unit test for the property 'Homeboundyn'
        }
        /// <summary>
        /// Test the property 'Assignedsexatbirth'
        /// </summary>
        [Test]
        public void AssignedsexatbirthTest()
        {
            // TODO unit test for the property 'Assignedsexatbirth'
        }
        /// <summary>
        /// Test the property 'Altfirstname'
        /// </summary>
        [Test]
        public void AltfirstnameTest()
        {
            // TODO unit test for the property 'Altfirstname'
        }
        /// <summary>
        /// Test the property 'Ethnicitycode'
        /// </summary>
        [Test]
        public void EthnicitycodeTest()
        {
            // TODO unit test for the property 'Ethnicitycode'
        }
        /// <summary>
        /// Test the property 'Industrycode'
        /// </summary>
        [Test]
        public void IndustrycodeTest()
        {
            // TODO unit test for the property 'Industrycode'
        }
        /// <summary>
        /// Test the property 'Language6392code'
        /// </summary>
        [Test]
        public void Language6392codeTest()
        {
            // TODO unit test for the property 'Language6392code'
        }
        /// <summary>
        /// Test the property 'Localpatientid'
        /// </summary>
        [Test]
        public void LocalpatientidTest()
        {
            // TODO unit test for the property 'Localpatientid'
        }
        /// <summary>
        /// Test the property 'Deceaseddate'
        /// </summary>
        [Test]
        public void DeceaseddateTest()
        {
            // TODO unit test for the property 'Deceaseddate'
        }
        /// <summary>
        /// Test the property 'Firstappointment'
        /// </summary>
        [Test]
        public void FirstappointmentTest()
        {
            // TODO unit test for the property 'Firstappointment'
        }
        /// <summary>
        /// Test the property 'Primaryproviderid'
        /// </summary>
        [Test]
        public void PrimaryprovideridTest()
        {
            // TODO unit test for the property 'Primaryproviderid'
        }
        /// <summary>
        /// Test the property 'Genderidentityother'
        /// </summary>
        [Test]
        public void GenderidentityotherTest()
        {
            // TODO unit test for the property 'Genderidentityother'
        }
        /// <summary>
        /// Test the property 'Portalstatus'
        /// </summary>
        [Test]
        public void PortalstatusTest()
        {
            // TODO unit test for the property 'Portalstatus'
        }
        /// <summary>
        /// Test the property 'Preferredpronouns'
        /// </summary>
        [Test]
        public void PreferredpronounsTest()
        {
            // TODO unit test for the property 'Preferredpronouns'
        }
        /// <summary>
        /// Test the property 'Lastappointment'
        /// </summary>
        [Test]
        public void LastappointmentTest()
        {
            // TODO unit test for the property 'Lastappointment'
        }
        /// <summary>
        /// Test the property 'Allpatientstatuses'
        /// </summary>
        [Test]
        public void AllpatientstatusesTest()
        {
            // TODO unit test for the property 'Allpatientstatuses'
        }
        /// <summary>
        /// Test the property 'Donotcallyn'
        /// </summary>
        [Test]
        public void DonotcallynTest()
        {
            // TODO unit test for the property 'Donotcallyn'
        }
        /// <summary>
        /// Test the property 'Primarydepartmentid'
        /// </summary>
        [Test]
        public void PrimarydepartmentidTest()
        {
            // TODO unit test for the property 'Primarydepartmentid'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Test]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }
        /// <summary>
        /// Test the property 'Lastemail'
        /// </summary>
        [Test]
        public void LastemailTest()
        {
            // TODO unit test for the property 'Lastemail'
        }
        /// <summary>
        /// Test the property 'Racecode'
        /// </summary>
        [Test]
        public void RacecodeTest()
        {
            // TODO unit test for the property 'Racecode'
        }
        /// <summary>
        /// Test the property 'Sexualorientation'
        /// </summary>
        [Test]
        public void SexualorientationTest()
        {
            // TODO unit test for the property 'Sexualorientation'
        }
        /// <summary>
        /// Test the property 'Genderidentity'
        /// </summary>
        [Test]
        public void GenderidentityTest()
        {
            // TODO unit test for the property 'Genderidentity'
        }
        /// <summary>
        /// Test the property 'Emailexistsyn'
        /// </summary>
        [Test]
        public void EmailexistsynTest()
        {
            // TODO unit test for the property 'Emailexistsyn'
        }
        /// <summary>
        /// Test the property 'Occupationcode'
        /// </summary>
        [Test]
        public void OccupationcodeTest()
        {
            // TODO unit test for the property 'Occupationcode'
        }
        /// <summary>
        /// Test the property 'Race'
        /// </summary>
        [Test]
        public void RaceTest()
        {
            // TODO unit test for the property 'Race'
        }
        /// <summary>
        /// Test the property 'Sexualorientationother'
        /// </summary>
        [Test]
        public void SexualorientationotherTest()
        {
            // TODO unit test for the property 'Sexualorientationother'
        }
        /// <summary>
        /// Test the property 'Patientid'
        /// </summary>
        [Test]
        public void PatientidTest()
        {
            // TODO unit test for the property 'Patientid'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Middlename'
        /// </summary>
        [Test]
        public void MiddlenameTest()
        {
            // TODO unit test for the property 'Middlename'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Suffix'
        /// </summary>
        [Test]
        public void SuffixTest()
        {
            // TODO unit test for the property 'Suffix'
        }
        /// <summary>
        /// Test the property 'Preferredname'
        /// </summary>
        [Test]
        public void PreferrednameTest()
        {
            // TODO unit test for the property 'Preferredname'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Test]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Test]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Zip'
        /// </summary>
        [Test]
        public void ZipTest()
        {
            // TODO unit test for the property 'Zip'
        }
        /// <summary>
        /// Test the property 'Countrycode'
        /// </summary>
        [Test]
        public void CountrycodeTest()
        {
            // TODO unit test for the property 'Countrycode'
        }
        /// <summary>
        /// Test the property 'Countrycode3166'
        /// </summary>
        [Test]
        public void Countrycode3166Test()
        {
            // TODO unit test for the property 'Countrycode3166'
        }
        /// <summary>
        /// Test the property 'Homephone'
        /// </summary>
        [Test]
        public void HomephoneTest()
        {
            // TODO unit test for the property 'Homephone'
        }
        /// <summary>
        /// Test the property 'Mobilephone'
        /// </summary>
        [Test]
        public void MobilephoneTest()
        {
            // TODO unit test for the property 'Mobilephone'
        }
        /// <summary>
        /// Test the property 'Hasmobileyn'
        /// </summary>
        [Test]
        public void HasmobileynTest()
        {
            // TODO unit test for the property 'Hasmobileyn'
        }
        /// <summary>
        /// Test the property 'Workphone'
        /// </summary>
        [Test]
        public void WorkphoneTest()
        {
            // TODO unit test for the property 'Workphone'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Ssn'
        /// </summary>
        [Test]
        public void SsnTest()
        {
            // TODO unit test for the property 'Ssn'
        }
        /// <summary>
        /// Test the property 'Racename'
        /// </summary>
        [Test]
        public void RacenameTest()
        {
            // TODO unit test for the property 'Racename'
        }
        /// <summary>
        /// Test the property 'Sex'
        /// </summary>
        [Test]
        public void SexTest()
        {
            // TODO unit test for the property 'Sex'
        }
        /// <summary>
        /// Test the property 'Dob'
        /// </summary>
        [Test]
        public void DobTest()
        {
            // TODO unit test for the property 'Dob'
        }
        /// <summary>
        /// Test the property 'Maritalstatus'
        /// </summary>
        [Test]
        public void MaritalstatusTest()
        {
            // TODO unit test for the property 'Maritalstatus'
        }
        /// <summary>
        /// Test the property 'Contactpreference'
        /// </summary>
        [Test]
        public void ContactpreferenceTest()
        {
            // TODO unit test for the property 'Contactpreference'
        }
        /// <summary>
        /// Test the property 'Contactname'
        /// </summary>
        [Test]
        public void ContactnameTest()
        {
            // TODO unit test for the property 'Contactname'
        }
        /// <summary>
        /// Test the property 'Contactrelationship'
        /// </summary>
        [Test]
        public void ContactrelationshipTest()
        {
            // TODO unit test for the property 'Contactrelationship'
        }
        /// <summary>
        /// Test the property 'Contacthomephone'
        /// </summary>
        [Test]
        public void ContacthomephoneTest()
        {
            // TODO unit test for the property 'Contacthomephone'
        }
        /// <summary>
        /// Test the property 'Contactmobilephone'
        /// </summary>
        [Test]
        public void ContactmobilephoneTest()
        {
            // TODO unit test for the property 'Contactmobilephone'
        }
        /// <summary>
        /// Test the property 'Nextkinname'
        /// </summary>
        [Test]
        public void NextkinnameTest()
        {
            // TODO unit test for the property 'Nextkinname'
        }
        /// <summary>
        /// Test the property 'Nextkinrelationship'
        /// </summary>
        [Test]
        public void NextkinrelationshipTest()
        {
            // TODO unit test for the property 'Nextkinrelationship'
        }
        /// <summary>
        /// Test the property 'Nextkinphone'
        /// </summary>
        [Test]
        public void NextkinphoneTest()
        {
            // TODO unit test for the property 'Nextkinphone'
        }
        /// <summary>
        /// Test the property 'Guardianfirstname'
        /// </summary>
        [Test]
        public void GuardianfirstnameTest()
        {
            // TODO unit test for the property 'Guardianfirstname'
        }
        /// <summary>
        /// Test the property 'Guardianmiddlename'
        /// </summary>
        [Test]
        public void GuardianmiddlenameTest()
        {
            // TODO unit test for the property 'Guardianmiddlename'
        }
        /// <summary>
        /// Test the property 'Guardianlastname'
        /// </summary>
        [Test]
        public void GuardianlastnameTest()
        {
            // TODO unit test for the property 'Guardianlastname'
        }
        /// <summary>
        /// Test the property 'Guardiansuffix'
        /// </summary>
        [Test]
        public void GuardiansuffixTest()
        {
            // TODO unit test for the property 'Guardiansuffix'
        }
        /// <summary>
        /// Test the property 'Guarantorfirstname'
        /// </summary>
        [Test]
        public void GuarantorfirstnameTest()
        {
            // TODO unit test for the property 'Guarantorfirstname'
        }
        /// <summary>
        /// Test the property 'Guarantormiddlename'
        /// </summary>
        [Test]
        public void GuarantormiddlenameTest()
        {
            // TODO unit test for the property 'Guarantormiddlename'
        }
        /// <summary>
        /// Test the property 'Guarantorlastname'
        /// </summary>
        [Test]
        public void GuarantorlastnameTest()
        {
            // TODO unit test for the property 'Guarantorlastname'
        }
        /// <summary>
        /// Test the property 'Guarantorsuffix'
        /// </summary>
        [Test]
        public void GuarantorsuffixTest()
        {
            // TODO unit test for the property 'Guarantorsuffix'
        }
        /// <summary>
        /// Test the property 'Guarantoraddress1'
        /// </summary>
        [Test]
        public void Guarantoraddress1Test()
        {
            // TODO unit test for the property 'Guarantoraddress1'
        }
        /// <summary>
        /// Test the property 'Guarantoraddress2'
        /// </summary>
        [Test]
        public void Guarantoraddress2Test()
        {
            // TODO unit test for the property 'Guarantoraddress2'
        }
        /// <summary>
        /// Test the property 'Guarantorcity'
        /// </summary>
        [Test]
        public void GuarantorcityTest()
        {
            // TODO unit test for the property 'Guarantorcity'
        }
        /// <summary>
        /// Test the property 'Guarantorstate'
        /// </summary>
        [Test]
        public void GuarantorstateTest()
        {
            // TODO unit test for the property 'Guarantorstate'
        }
        /// <summary>
        /// Test the property 'Guarantorzip'
        /// </summary>
        [Test]
        public void GuarantorzipTest()
        {
            // TODO unit test for the property 'Guarantorzip'
        }
        /// <summary>
        /// Test the property 'Guarantorcountrycode'
        /// </summary>
        [Test]
        public void GuarantorcountrycodeTest()
        {
            // TODO unit test for the property 'Guarantorcountrycode'
        }
        /// <summary>
        /// Test the property 'Guarantorcountrycode3166'
        /// </summary>
        [Test]
        public void Guarantorcountrycode3166Test()
        {
            // TODO unit test for the property 'Guarantorcountrycode3166'
        }
        /// <summary>
        /// Test the property 'Guarantordob'
        /// </summary>
        [Test]
        public void GuarantordobTest()
        {
            // TODO unit test for the property 'Guarantordob'
        }
        /// <summary>
        /// Test the property 'Guarantorssn'
        /// </summary>
        [Test]
        public void GuarantorssnTest()
        {
            // TODO unit test for the property 'Guarantorssn'
        }
        /// <summary>
        /// Test the property 'Guarantoremail'
        /// </summary>
        [Test]
        public void GuarantoremailTest()
        {
            // TODO unit test for the property 'Guarantoremail'
        }
        /// <summary>
        /// Test the property 'Guarantorphone'
        /// </summary>
        [Test]
        public void GuarantorphoneTest()
        {
            // TODO unit test for the property 'Guarantorphone'
        }
        /// <summary>
        /// Test the property 'Guarantorrelationshiptopatient'
        /// </summary>
        [Test]
        public void GuarantorrelationshiptopatientTest()
        {
            // TODO unit test for the property 'Guarantorrelationshiptopatient'
        }
        /// <summary>
        /// Test the property 'Guarantoraddresssameaspatient'
        /// </summary>
        [Test]
        public void GuarantoraddresssameaspatientTest()
        {
            // TODO unit test for the property 'Guarantoraddresssameaspatient'
        }
        /// <summary>
        /// Test the property 'Registrationdate'
        /// </summary>
        [Test]
        public void RegistrationdateTest()
        {
            // TODO unit test for the property 'Registrationdate'
        }
        /// <summary>
        /// Test the property 'Departmentid'
        /// </summary>
        [Test]
        public void DepartmentidTest()
        {
            // TODO unit test for the property 'Departmentid'
        }
        /// <summary>
        /// Test the property 'Portaltermsonfile'
        /// </summary>
        [Test]
        public void PortaltermsonfileTest()
        {
            // TODO unit test for the property 'Portaltermsonfile'
        }
        /// <summary>
        /// Test the property 'Portalsignatureonfile'
        /// </summary>
        [Test]
        public void PortalsignatureonfileTest()
        {
            // TODO unit test for the property 'Portalsignatureonfile'
        }
        /// <summary>
        /// Test the property 'Privacyinformationverified'
        /// </summary>
        [Test]
        public void PrivacyinformationverifiedTest()
        {
            // TODO unit test for the property 'Privacyinformationverified'
        }
        /// <summary>
        /// Test the property 'Medicationhistoryconsentverified'
        /// </summary>
        [Test]
        public void MedicationhistoryconsentverifiedTest()
        {
            // TODO unit test for the property 'Medicationhistoryconsentverified'
        }
        /// <summary>
        /// Test the property 'Maritalstatusname'
        /// </summary>
        [Test]
        public void MaritalstatusnameTest()
        {
            // TODO unit test for the property 'Maritalstatusname'
        }
        /// <summary>
        /// Test the property 'Employerid'
        /// </summary>
        [Test]
        public void EmployeridTest()
        {
            // TODO unit test for the property 'Employerid'
        }
        /// <summary>
        /// Test the property 'Employerphone'
        /// </summary>
        [Test]
        public void EmployerphoneTest()
        {
            // TODO unit test for the property 'Employerphone'
        }
        /// <summary>
        /// Test the property 'Guarantoremployerid'
        /// </summary>
        [Test]
        public void GuarantoremployeridTest()
        {
            // TODO unit test for the property 'Guarantoremployerid'
        }
        /// <summary>
        /// Test the property 'Employername'
        /// </summary>
        [Test]
        public void EmployernameTest()
        {
            // TODO unit test for the property 'Employername'
        }
        /// <summary>
        /// Test the property 'Employeraddress'
        /// </summary>
        [Test]
        public void EmployeraddressTest()
        {
            // TODO unit test for the property 'Employeraddress'
        }
        /// <summary>
        /// Test the property 'Employercity'
        /// </summary>
        [Test]
        public void EmployercityTest()
        {
            // TODO unit test for the property 'Employercity'
        }
        /// <summary>
        /// Test the property 'Portalaccessgiven'
        /// </summary>
        [Test]
        public void PortalaccessgivenTest()
        {
            // TODO unit test for the property 'Portalaccessgiven'
        }

    }

}
