/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing PatientCcda
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientCcdaTests
    {
        // TODO uncomment below to declare an instance variable for PatientCcda
        //private PatientCcda instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientCcda
            //instance = new PatientCcda();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientCcda
        /// </summary>
        [Test]
        public void PatientCcdaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientCcda
            //Assert.IsInstanceOfType<PatientCcda> (instance, "variable 'instance' is a PatientCcda");
        }


        /// <summary>
        /// Test the property 'Ccda'
        /// </summary>
        [Test]
        public void CcdaTest()
        {
            // TODO unit test for the property 'Ccda'
        }

    }

}
