/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing PatientMedicalHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientMedicalHistoryTests
    {
        // TODO uncomment below to declare an instance variable for PatientMedicalHistory
        //private PatientMedicalHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientMedicalHistory
            //instance = new PatientMedicalHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientMedicalHistory
        /// </summary>
        [Test]
        public void PatientMedicalHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientMedicalHistory
            //Assert.IsInstanceOfType<PatientMedicalHistory> (instance, "variable 'instance' is a PatientMedicalHistory");
        }


        /// <summary>
        /// Test the property 'Sectionnote'
        /// </summary>
        [Test]
        public void SectionnoteTest()
        {
            // TODO unit test for the property 'Sectionnote'
        }
        /// <summary>
        /// Test the property 'Questions'
        /// </summary>
        [Test]
        public void QuestionsTest()
        {
            // TODO unit test for the property 'Questions'
        }

    }

}
