/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing PatientMedication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PatientMedicationTests
    {
        // TODO uncomment below to declare an instance variable for PatientMedication
        //private PatientMedication instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientMedication
            //instance = new PatientMedication();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientMedication
        /// </summary>
        [Test]
        public void PatientMedicationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PatientMedication
            //Assert.IsInstanceOfType<PatientMedication> (instance, "variable 'instance' is a PatientMedication");
        }


        /// <summary>
        /// Test the property 'Nomedicationsreported'
        /// </summary>
        [Test]
        public void NomedicationsreportedTest()
        {
            // TODO unit test for the property 'Nomedicationsreported'
        }
        /// <summary>
        /// Test the property 'Medications'
        /// </summary>
        [Test]
        public void MedicationsTest()
        {
            // TODO unit test for the property 'Medications'
        }
        /// <summary>
        /// Test the property 'Sectionnote'
        /// </summary>
        [Test]
        public void SectionnoteTest()
        {
            // TODO unit test for the property 'Sectionnote'
        }
        /// <summary>
        /// Test the property 'Lastupdated'
        /// </summary>
        [Test]
        public void LastupdatedTest()
        {
            // TODO unit test for the property 'Lastupdated'
        }
        /// <summary>
        /// Test the property 'Patientdownloadconsent'
        /// </summary>
        [Test]
        public void PatientdownloadconsentTest()
        {
            // TODO unit test for the property 'Patientdownloadconsent'
        }
        /// <summary>
        /// Test the property 'Patientneedsdownloadconsent'
        /// </summary>
        [Test]
        public void PatientneedsdownloadconsentTest()
        {
            // TODO unit test for the property 'Patientneedsdownloadconsent'
        }
        /// <summary>
        /// Test the property 'Lastdownloadeddate'
        /// </summary>
        [Test]
        public void LastdownloadeddateTest()
        {
            // TODO unit test for the property 'Lastdownloadeddate'
        }
        /// <summary>
        /// Test the property 'Lastdownloaddenied'
        /// </summary>
        [Test]
        public void LastdownloaddeniedTest()
        {
            // TODO unit test for the property 'Lastdownloaddenied'
        }
        /// <summary>
        /// Test the property 'Lastdownloaddenialreason'
        /// </summary>
        [Test]
        public void LastdownloaddenialreasonTest()
        {
            // TODO unit test for the property 'Lastdownloaddenialreason'
        }

    }

}
