/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing ProblemsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProblemsListTests
    {
        // TODO uncomment below to declare an instance variable for ProblemsList
        //private ProblemsList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProblemsList
            //instance = new ProblemsList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProblemsList
        /// </summary>
        [Test]
        public void ProblemsListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProblemsList
            //Assert.IsInstanceOfType<ProblemsList> (instance, "variable 'instance' is a ProblemsList");
        }


        /// <summary>
        /// Test the property 'Totalcount'
        /// </summary>
        [Test]
        public void TotalcountTest()
        {
            // TODO unit test for the property 'Totalcount'
        }
        /// <summary>
        /// Test the property 'Problems'
        /// </summary>
        [Test]
        public void ProblemsTest()
        {
            // TODO unit test for the property 'Problems'
        }

    }

}
