/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ProceduresList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProceduresListTests
    {
        // TODO uncomment below to declare an instance variable for ProceduresList
        //private ProceduresList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProceduresList
            //instance = new ProceduresList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProceduresList
        /// </summary>
        [Test]
        public void ProceduresListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProceduresList
            //Assert.IsInstanceOfType<ProceduresList> (instance, "variable 'instance' is a ProceduresList");
        }


        /// <summary>
        /// Test the property 'Sectionnote'
        /// </summary>
        [Test]
        public void SectionnoteTest()
        {
            // TODO unit test for the property 'Sectionnote'
        }
        /// <summary>
        /// Test the property 'Procedures'
        /// </summary>
        [Test]
        public void ProceduresTest()
        {
            // TODO unit test for the property 'Procedures'
        }

    }

}
