/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Jacrys.AthenaSharp.Api;
using Jacrys.AthenaSharp.Model;
using Jacrys.AthenaSharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Jacrys.AthenaSharp.Test
{
    /// <summary>
    ///  Class for testing Provider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProviderTests
    {
        // TODO uncomment below to declare an instance variable for Provider
        //private Provider instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Provider
            //instance = new Provider();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Provider
        /// </summary>
        [Test]
        public void ProviderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Provider
            //Assert.IsInstanceOfType<Provider> (instance, "variable 'instance' is a Provider");
        }


        /// <summary>
        /// Test the property 'Billable'
        /// </summary>
        [Test]
        public void BillableTest()
        {
            // TODO unit test for the property 'Billable'
        }
        /// <summary>
        /// Test the property 'Ansispecialtycode'
        /// </summary>
        [Test]
        public void AnsispecialtycodeTest()
        {
            // TODO unit test for the property 'Ansispecialtycode'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Entitytype'
        /// </summary>
        [Test]
        public void EntitytypeTest()
        {
            // TODO unit test for the property 'Entitytype'
        }
        /// <summary>
        /// Test the property 'Otherprovideridlist'
        /// </summary>
        [Test]
        public void OtherprovideridlistTest()
        {
            // TODO unit test for the property 'Otherprovideridlist'
        }
        /// <summary>
        /// Test the property 'Ansinamecode'
        /// </summary>
        [Test]
        public void AnsinamecodeTest()
        {
            // TODO unit test for the property 'Ansinamecode'
        }
        /// <summary>
        /// Test the property 'Displayname'
        /// </summary>
        [Test]
        public void DisplaynameTest()
        {
            // TODO unit test for the property 'Displayname'
        }
        /// <summary>
        /// Test the property 'Homedepartment'
        /// </summary>
        [Test]
        public void HomedepartmentTest()
        {
            // TODO unit test for the property 'Homedepartment'
        }
        /// <summary>
        /// Test the property 'Providerid'
        /// </summary>
        [Test]
        public void ProvideridTest()
        {
            // TODO unit test for the property 'Providerid'
        }
        /// <summary>
        /// Test the property 'Providertypeid'
        /// </summary>
        [Test]
        public void ProvidertypeidTest()
        {
            // TODO unit test for the property 'Providertypeid'
        }
        /// <summary>
        /// Test the property 'Providerusername'
        /// </summary>
        [Test]
        public void ProviderusernameTest()
        {
            // TODO unit test for the property 'Providerusername'
        }
        /// <summary>
        /// Test the property 'Supervisingproviderid'
        /// </summary>
        [Test]
        public void SupervisingprovideridTest()
        {
            // TODO unit test for the property 'Supervisingproviderid'
        }
        /// <summary>
        /// Test the property 'Providertype'
        /// </summary>
        [Test]
        public void ProvidertypeTest()
        {
            // TODO unit test for the property 'Providertype'
        }
        /// <summary>
        /// Test the property 'Createencounterprovideridlist'
        /// </summary>
        [Test]
        public void CreateencounterprovideridlistTest()
        {
            // TODO unit test for the property 'Createencounterprovideridlist'
        }
        /// <summary>
        /// Test the property 'Schedulingname'
        /// </summary>
        [Test]
        public void SchedulingnameTest()
        {
            // TODO unit test for the property 'Schedulingname'
        }
        /// <summary>
        /// Test the property 'Usualdepartmentid'
        /// </summary>
        [Test]
        public void UsualdepartmentidTest()
        {
            // TODO unit test for the property 'Usualdepartmentid'
        }
        /// <summary>
        /// Test the property 'Createencounteroncheckinyn'
        /// </summary>
        [Test]
        public void CreateencounteroncheckinynTest()
        {
            // TODO unit test for the property 'Createencounteroncheckinyn'
        }
        /// <summary>
        /// Test the property 'Specialty'
        /// </summary>
        [Test]
        public void SpecialtyTest()
        {
            // TODO unit test for the property 'Specialty'
        }
        /// <summary>
        /// Test the property 'Hideinportalyn'
        /// </summary>
        [Test]
        public void HideinportalynTest()
        {
            // TODO unit test for the property 'Hideinportalyn'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Npi'
        /// </summary>
        [Test]
        public void NpiTest()
        {
            // TODO unit test for the property 'Npi'
        }
        /// <summary>
        /// Test the property 'Providergrouplist'
        /// </summary>
        [Test]
        public void ProvidergrouplistTest()
        {
            // TODO unit test for the property 'Providergrouplist'
        }
        /// <summary>
        /// Test the property 'Federalidnumber'
        /// </summary>
        [Test]
        public void FederalidnumberTest()
        {
            // TODO unit test for the property 'Federalidnumber'
        }
        /// <summary>
        /// Test the property 'Supervisingproviderusername'
        /// </summary>
        [Test]
        public void SupervisingproviderusernameTest()
        {
            // TODO unit test for the property 'Supervisingproviderusername'
        }

    }

}
