/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Template
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TemplateTests
    {
        // TODO uncomment below to declare an instance variable for Template
        //private Template instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Template
            //instance = new Template();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Template
        /// </summary>
        [Test]
        public void TemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Template
            //Assert.IsInstanceOfType<Template> (instance, "variable 'instance' is a Template");
        }


        /// <summary>
        /// Test the property 'Templateid'
        /// </summary>
        [Test]
        public void TemplateidTest()
        {
            // TODO unit test for the property 'Templateid'
        }
        /// <summary>
        /// Test the property 'Templatename'
        /// </summary>
        [Test]
        public void TemplatenameTest()
        {
            // TODO unit test for the property 'Templatename'
        }

    }

}
