/* 
 * athenahealth More Disruption Please (MDP) API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing VitalsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VitalsListTests
    {
        // TODO uncomment below to declare an instance variable for VitalsList
        //private VitalsList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VitalsList
            //instance = new VitalsList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VitalsList
        /// </summary>
        [Test]
        public void VitalsListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VitalsList
            //Assert.IsInstanceOfType<VitalsList> (instance, "variable 'instance' is a VitalsList");
        }


        /// <summary>
        /// Test the property 'Totalcount'
        /// </summary>
        [Test]
        public void TotalcountTest()
        {
            // TODO unit test for the property 'Totalcount'
        }
        /// <summary>
        /// Test the property 'Vitals'
        /// </summary>
        [Test]
        public void VitalsTest()
        {
            // TODO unit test for the property 'Vitals'
        }

    }

}
